<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Linq" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pedido_\Shared\Web\ObtenerPedido\Infraestructura\Adaptador\" />
    <Folder Include="Pedido_\Shared\Web\ObtenerPedido\Infraestructura\Persistencia\" />
    <Folder Include="Pedido_\Shared\Web\ObtenerPedido\NewFolder\" />
    <Folder Include="Rol_\CasosUso\RegistarRol_\Dominio\Exceptions\" />
    <Folder Include="Rol_\CasosUso\RegistarRol_\Dominio\ValueObjects\" />
  </ItemGroup>

</Project>
